version: "3.6"

services:
  app:
    build: .
    image: computer-manager-api
    ports:
      - "8080:8080"
    environment:
      COMPUTER_MANAGER_API_POSTGRES_DSN: postgres://postgres:postgres@database:5432/computer_manager_api
      COMPUTER_MANAGER_API_NOTIFICATION_URL: http://notification-service:8080/api/notify
    depends_on:
      - database
  database:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: computer_manager_api
    ports:
      - "5433:5432"
  notification-service:
    image: greenbone/exercise-admin-notification

